analytics:
  reporting_enabled: false

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  storage:
    filesystem:
      chunks_directory: "/opt/loki/data/chunks"
      rules_directory: "/opt/loki/data/rules"
  replication_factor: 1
  ring:
    kvstore:
      store: "inmemory"

schema_config:
  configs:
    - from: "2020-10-24"
      store: "boltdb-shipper"
      object_store: "filesystem"
      schema: "v11"
      index:
        prefix: "index_"
        period: "24h"

ingester:
  wal:
    enabled: true
    dir: /opt/loki/data/wal
  lifecycler:
    address: 0.0.0.0
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s
  max_transfer_retries: 0

storage_config:
  boltdb_shipper:
    active_index_directory: /opt/loki/data/boltdb-shipper-active
    cache_location: /opt/loki/data//boltdb-shipper-cache
    cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: filesystem
  filesystem:
    directory: /opt/loki/data/chunks

compactor:
  working_directory: /opt/loki/data/boltdb-shipper-compactor
  shared_store: filesystem

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s