server:
  host: "0.0.0.0"
  port:
    grpc: 8080
    metric: 8081
    gw: 8082
    files: 8083
clients:
  session: "session-svc:8080"
queue:
  urls: [
    "nats://nats-node1:4222",
    "nats://nats-node2:4222",
    "nats://nats-node3:4222",
  ]
  username: "user_svc"
  password: "super_duper_secret_key"
db:
  migrate_dir: "migrate"
  driver: "postgres"
  cockroach:
    user: "user_svc"
    password: "user_pass"
    host: "cockroach-node2"
    port: 26257
    database: "user_db"
    parameters:
      application_name: "user_svc"
      mode: "require"
file_store:
  secure: false
  endpoint: "minio-node1:9000"
  access_key: "test_svc"
  secret_key: "test_pass"
dev_mode: true
