// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: api/twit/v1/twit.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Twit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId  string               `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Text      string               `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Twit) Reset() {
	*x = Twit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_twit_v1_twit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Twit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Twit) ProtoMessage() {}

func (x *Twit) ProtoReflect() protoreflect.Message {
	mi := &file_api_twit_v1_twit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Twit.ProtoReflect.Descriptor instead.
func (*Twit) Descriptor() ([]byte, []int) {
	return file_api_twit_v1_twit_proto_rawDescGZIP(), []int{0}
}

func (x *Twit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Twit) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Twit) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Twit) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Twit) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type TwitPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *TwitPostRequest) Reset() {
	*x = TwitPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_twit_v1_twit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwitPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwitPostRequest) ProtoMessage() {}

func (x *TwitPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_twit_v1_twit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwitPostRequest.ProtoReflect.Descriptor instead.
func (*TwitPostRequest) Descriptor() ([]byte, []int) {
	return file_api_twit_v1_twit_proto_rawDescGZIP(), []int{1}
}

func (x *TwitPostRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TwitPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Twit *Twit `protobuf:"bytes,1,opt,name=twit,proto3" json:"twit,omitempty"`
}

func (x *TwitPostResponse) Reset() {
	*x = TwitPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_twit_v1_twit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwitPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwitPostResponse) ProtoMessage() {}

func (x *TwitPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_twit_v1_twit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwitPostResponse.ProtoReflect.Descriptor instead.
func (*TwitPostResponse) Descriptor() ([]byte, []int) {
	return file_api_twit_v1_twit_proto_rawDescGZIP(), []int{2}
}

func (x *TwitPostResponse) GetTwit() *Twit {
	if x != nil {
		return x.Twit
	}
	return nil
}

type TwitGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TwitGetRequest) Reset() {
	*x = TwitGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_twit_v1_twit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwitGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwitGetRequest) ProtoMessage() {}

func (x *TwitGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_twit_v1_twit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwitGetRequest.ProtoReflect.Descriptor instead.
func (*TwitGetRequest) Descriptor() ([]byte, []int) {
	return file_api_twit_v1_twit_proto_rawDescGZIP(), []int{3}
}

func (x *TwitGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TwitGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Twit *Twit `protobuf:"bytes,1,opt,name=twit,proto3" json:"twit,omitempty"`
}

func (x *TwitGetResponse) Reset() {
	*x = TwitGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_twit_v1_twit_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwitGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwitGetResponse) ProtoMessage() {}

func (x *TwitGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_twit_v1_twit_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwitGetResponse.ProtoReflect.Descriptor instead.
func (*TwitGetResponse) Descriptor() ([]byte, []int) {
	return file_api_twit_v1_twit_proto_rawDescGZIP(), []int{4}
}

func (x *TwitGetResponse) GetTwit() *Twit {
	if x != nil {
		return x.Twit
	}
	return nil
}

type TwitUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *TwitUpdateRequest) Reset() {
	*x = TwitUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_twit_v1_twit_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwitUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwitUpdateRequest) ProtoMessage() {}

func (x *TwitUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_twit_v1_twit_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwitUpdateRequest.ProtoReflect.Descriptor instead.
func (*TwitUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_twit_v1_twit_proto_rawDescGZIP(), []int{5}
}

func (x *TwitUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TwitUpdateRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TwitUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Twit *Twit `protobuf:"bytes,1,opt,name=twit,proto3" json:"twit,omitempty"`
}

func (x *TwitUpdateResponse) Reset() {
	*x = TwitUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_twit_v1_twit_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwitUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwitUpdateResponse) ProtoMessage() {}

func (x *TwitUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_twit_v1_twit_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwitUpdateResponse.ProtoReflect.Descriptor instead.
func (*TwitUpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_twit_v1_twit_proto_rawDescGZIP(), []int{6}
}

func (x *TwitUpdateResponse) GetTwit() *Twit {
	if x != nil {
		return x.Twit
	}
	return nil
}

type TwitDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TwitDeleteRequest) Reset() {
	*x = TwitDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_twit_v1_twit_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwitDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwitDeleteRequest) ProtoMessage() {}

func (x *TwitDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_twit_v1_twit_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwitDeleteRequest.ProtoReflect.Descriptor instead.
func (*TwitDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_twit_v1_twit_proto_rawDescGZIP(), []int{7}
}

func (x *TwitDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TwitDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TwitDeleteResponse) Reset() {
	*x = TwitDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_twit_v1_twit_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwitDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwitDeleteResponse) ProtoMessage() {}

func (x *TwitDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_twit_v1_twit_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwitDeleteResponse.ProtoReflect.Descriptor instead.
func (*TwitDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_twit_v1_twit_proto_rawDescGZIP(), []int{8}
}

var File_api_twit_v1_twit_proto protoreflect.FileDescriptor

var file_api_twit_v1_twit_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x77, 0x69, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x77,
	0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x77,
	0x69, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbd, 0x01, 0x0a, 0x04, 0x54, 0x77, 0x69, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x25, 0x0a, 0x0f, 0x54, 0x77, 0x69, 0x74, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x39, 0x0a,
	0x10, 0x54, 0x77, 0x69, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x77, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x77,
	0x69, 0x74, 0x52, 0x04, 0x74, 0x77, 0x69, 0x74, 0x22, 0x20, 0x0a, 0x0e, 0x54, 0x77, 0x69, 0x74,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x0f, 0x54, 0x77,
	0x69, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a,
	0x04, 0x74, 0x77, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x77, 0x69, 0x74, 0x52, 0x04,
	0x74, 0x77, 0x69, 0x74, 0x22, 0x37, 0x0a, 0x11, 0x54, 0x77, 0x69, 0x74, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x3b, 0x0a,
	0x12, 0x54, 0x77, 0x69, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x77, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x54, 0x77, 0x69, 0x74, 0x52, 0x04, 0x74, 0x77, 0x69, 0x74, 0x22, 0x23, 0x0a, 0x11, 0x54, 0x77,
	0x69, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x14, 0x0a, 0x12, 0x54, 0x77, 0x69, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xbe, 0x02, 0x0a, 0x07, 0x54, 0x77, 0x69, 0x74, 0x41, 0x50,
	0x49, 0x12, 0x49, 0x0a, 0x08, 0x54, 0x77, 0x69, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x1c, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x77, 0x69, 0x74,
	0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x77, 0x69, 0x74, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x07,
	0x54, 0x77, 0x69, 0x74, 0x47, 0x65, 0x74, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x77,
	0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x77, 0x69, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x54, 0x77, 0x69, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0a, 0x54, 0x77, 0x69, 0x74, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x77, 0x69, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x77, 0x69, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0a, 0x54, 0x77, 0x69, 0x74, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x2e, 0x76,
	0x31, 0x2e, 0x54, 0x77, 0x69, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x2e, 0x76,
	0x31, 0x2e, 0x54, 0x77, 0x69, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x22, 0x5a, 0x20, 0x61, 0x6e, 0x6b, 0x2f, 0x62, 0x61,
	0x63, 0x6b, 0x2d, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x74, 0x77, 0x69, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_twit_v1_twit_proto_rawDescOnce sync.Once
	file_api_twit_v1_twit_proto_rawDescData = file_api_twit_v1_twit_proto_rawDesc
)

func file_api_twit_v1_twit_proto_rawDescGZIP() []byte {
	file_api_twit_v1_twit_proto_rawDescOnce.Do(func() {
		file_api_twit_v1_twit_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_twit_v1_twit_proto_rawDescData)
	})
	return file_api_twit_v1_twit_proto_rawDescData
}

var file_api_twit_v1_twit_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_twit_v1_twit_proto_goTypes = []interface{}{
	(*Twit)(nil),                // 0: api.twit.v1.Twit
	(*TwitPostRequest)(nil),     // 1: api.twit.v1.TwitPostRequest
	(*TwitPostResponse)(nil),    // 2: api.twit.v1.TwitPostResponse
	(*TwitGetRequest)(nil),      // 3: api.twit.v1.TwitGetRequest
	(*TwitGetResponse)(nil),     // 4: api.twit.v1.TwitGetResponse
	(*TwitUpdateRequest)(nil),   // 5: api.twit.v1.TwitUpdateRequest
	(*TwitUpdateResponse)(nil),  // 6: api.twit.v1.TwitUpdateResponse
	(*TwitDeleteRequest)(nil),   // 7: api.twit.v1.TwitDeleteRequest
	(*TwitDeleteResponse)(nil),  // 8: api.twit.v1.TwitDeleteResponse
	(*timestamp.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_api_twit_v1_twit_proto_depIdxs = []int32{
	9, // 0: api.twit.v1.Twit.created_at:type_name -> google.protobuf.Timestamp
	9, // 1: api.twit.v1.Twit.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: api.twit.v1.TwitPostResponse.twit:type_name -> api.twit.v1.Twit
	0, // 3: api.twit.v1.TwitGetResponse.twit:type_name -> api.twit.v1.Twit
	0, // 4: api.twit.v1.TwitUpdateResponse.twit:type_name -> api.twit.v1.Twit
	1, // 5: api.twit.v1.TwitAPI.TwitPost:input_type -> api.twit.v1.TwitPostRequest
	3, // 6: api.twit.v1.TwitAPI.TwitGet:input_type -> api.twit.v1.TwitGetRequest
	5, // 7: api.twit.v1.TwitAPI.TwitUpdate:input_type -> api.twit.v1.TwitUpdateRequest
	7, // 8: api.twit.v1.TwitAPI.TwitDelete:input_type -> api.twit.v1.TwitDeleteRequest
	2, // 9: api.twit.v1.TwitAPI.TwitPost:output_type -> api.twit.v1.TwitPostResponse
	4, // 10: api.twit.v1.TwitAPI.TwitGet:output_type -> api.twit.v1.TwitGetResponse
	6, // 11: api.twit.v1.TwitAPI.TwitUpdate:output_type -> api.twit.v1.TwitUpdateResponse
	8, // 12: api.twit.v1.TwitAPI.TwitDelete:output_type -> api.twit.v1.TwitDeleteResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_twit_v1_twit_proto_init() }
func file_api_twit_v1_twit_proto_init() {
	if File_api_twit_v1_twit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_twit_v1_twit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Twit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_twit_v1_twit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TwitPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_twit_v1_twit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TwitPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_twit_v1_twit_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TwitGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_twit_v1_twit_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TwitGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_twit_v1_twit_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TwitUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_twit_v1_twit_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TwitUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_twit_v1_twit_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TwitDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_twit_v1_twit_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TwitDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_twit_v1_twit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_twit_v1_twit_proto_goTypes,
		DependencyIndexes: file_api_twit_v1_twit_proto_depIdxs,
		MessageInfos:      file_api_twit_v1_twit_proto_msgTypes,
	}.Build()
	File_api_twit_v1_twit_proto = out.File
	file_api_twit_v1_twit_proto_rawDesc = nil
	file_api_twit_v1_twit_proto_goTypes = nil
	file_api_twit_v1_twit_proto_depIdxs = nil
}
